language: node_js
node_js:
  - "9"
  - "10"
before_script:
  - npm run build
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npx version-from-git --travis
deploy:
  - provider: npm
    api_key:
      secure: "Me1CxKcp/314HdbxHvmJKBUKA2LF15RY/y8E7UpiY+aEkuvvFVorVtf7LL7q32lj/xdpY+TwVrd8XhhS32mr6gXnpuwosVOrkQyGyRXJTzuaZRQdqMK+GvdQ+POvyDoFOqlGM6oXWamTNWr72cvF+cdSWJQEKeKnd0+iKZImJGia1Z0QkzXVKxw0SS+mZRUrX/qNpYB+8TSHHlZKAGw932ymz9EKdlsKgJwQaSOYKPgU/63VZNDRCq8ko79JJkbxrQ1HzE+flLFK02bqsVvoYf6uI48JQLMwwG+D4B7Ei/MuAZ2T+MUOs3k9ZSedg9uyCpJK035C/t8a4sDUd9NBi5QBaBJ32mPSB8nbK0pKudCbW/crdGOzl8Zvf8L4rFgPCaI/gDgx2f4sj0m4MIcL2cUn7YDKwRcTRP0R8kVYVAop7Adhkqw2JE+VbbETBSSz3zhP/vmjCE1r8Hhl/Hp6YTiJ2UXzsLR7cm24CQZsoOXAthV5JyGcBjMK8YTd444FAZ8bG1Ag3N67Kop0AJ2F3qmM4+U77YlId8ZmYVQWUoBzC8FuTViOP26wcxeCZLww8XZ3AtFmWu8dfMUFzQdlX6dqkccD5GU7Vv5LQJth8e+0BoYsATPe8vjbxYkkv8Z8lxOStMYXOBqyDDPVSbflu0ZrI/4AQM0RSishjRpBOmE="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "Me1CxKcp/314HdbxHvmJKBUKA2LF15RY/y8E7UpiY+aEkuvvFVorVtf7LL7q32lj/xdpY+TwVrd8XhhS32mr6gXnpuwosVOrkQyGyRXJTzuaZRQdqMK+GvdQ+POvyDoFOqlGM6oXWamTNWr72cvF+cdSWJQEKeKnd0+iKZImJGia1Z0QkzXVKxw0SS+mZRUrX/qNpYB+8TSHHlZKAGw932ymz9EKdlsKgJwQaSOYKPgU/63VZNDRCq8ko79JJkbxrQ1HzE+flLFK02bqsVvoYf6uI48JQLMwwG+D4B7Ei/MuAZ2T+MUOs3k9ZSedg9uyCpJK035C/t8a4sDUd9NBi5QBaBJ32mPSB8nbK0pKudCbW/crdGOzl8Zvf8L4rFgPCaI/gDgx2f4sj0m4MIcL2cUn7YDKwRcTRP0R8kVYVAop7Adhkqw2JE+VbbETBSSz3zhP/vmjCE1r8Hhl/Hp6YTiJ2UXzsLR7cm24CQZsoOXAthV5JyGcBjMK8YTd444FAZ8bG1Ag3N67Kop0AJ2F3qmM4+U77YlId8ZmYVQWUoBzC8FuTViOP26wcxeCZLww8XZ3AtFmWu8dfMUFzQdlX6dqkccD5GU7Vv5LQJth8e+0BoYsATPe8vjbxYkkv8Z8lxOStMYXOBqyDDPVSbflu0ZrI/4AQM0RSishjRpBOmE="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "qpDMagUO/iel6QW38U75MkHCsI71fFm2fwEak4W+vteTrB3kWvLKDK3Mn3JqViPtDBD4978hO4cLJNpXsELwXvNVYZ1tJH3QQyxiDIO5XypbhpVfCyrbDmV3C59tUpDuRfaONYztceqtmErT6DVAtzrymfjof0GM3C6EnRulfqNc1Q/FN5dNL3+DYF8NLADljDWDjVlDeDjr4e924T5FcgaJztJverdnblS+0OahRVz2lxNgPhXbQF+gbDBCg63seC4gumFlRYrVSMbBIbg7GvZ3/GafnAzN0Wb7lC+kzAE+esO/TLFiXYQ8P7O7fvTzQPW/Fjm7S0E575H5me+bgVQgr+D6fluJDuiFjQXkhebanrVaH3K+ah4ix3OL5/7RDhIOQoXf7CwLJhpaOCT/wMDiBm0rKDL0C+Xdn2+AKV502ZFvUjxdrd9kLT+3F8Ykr/dLOaiZUKJNVzUb3i1UUOaSH/cGIKY17hvkDR3MzS/+gIkQuEpwjSQpnunW/iR6n0hdNk+zmdqWYLiKZiU1gsEwhRzS9klQaOtvxyYdl9hrma/BeB+EOwGGb2La9pvrunmW2si/9NIloj2oM92WDtcpOzu3O+JIO1PMAiMFfd1ECSud5fg7plMLJNE1Cy1nTbs8MYXAf/BiFZNemYsyNORAtSNpLaN70Nw8ToPb060="
    on:
      tags: true
    skip_cleanup: true
